sourcefuse/loopback4-s3

.eslintignore, package-lock.json, package.json
Upgraded loopback dependencies using `lb4 update`
Fixed eslint issues
=> upgraded dependencies, lint fixes

package-lock.json, package.json
Description
Updated versions of All Loopback packages.
Type of change
=> fix(version): updated versions of all loopback packages

README.md, package-lock.json, package.json, src/providers/aws-s3.provider.ts, src/types.ts
signature version required by AWS have been added in the config and readme has been updated accordingly.
Packages updations also done.
=> added signature version

README.md, package-lock.json, package.json, src/providers/aws-s3.provider.ts, src/types.ts
Reverts sourcefuse/loopback4-s3#14
=> Revert "fix(loopback4-s3): dependency removed from aws-sdk #13"

src/providers/aws-s3.provider.ts
=> fix: prettier fixed

README.md, src/__tests__/acceptance/aws-s3.provider.acceptance.ts, src/__tests__/unit/aws.s3.provider.unit.ts
Update readme for v3 migration
Fixes # (issue)
=> docs(component): update readme for v3 migration

README.md
Update readme to add requirement for cmake 3.1+
=> docs(core): add cmake requirement in readme

src/providers/aws-s3.provider.ts
Fix config spread in constructor for s3 client
=> fix(core): fix config spread in s3 constructor

package.json
- add patch-package to peer deps so that post install doesn't fail
gh-0
=> chore(deps): add patch-package to peer dependencies

package-lock.json, package.json
=> chore(ci-cd): semantic slack bot

package.json
GH-00
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
=> fix(ci-cd): slack bot for semantic release

.cz-config.js, package-lock.json, package.json, patches/ramda+0.28.0.patch
- update all deps
- apply patch for ramda and add patch-package to peer deps
- add ovrerides section to package json to solve vulnerabilities
=> chore(deps): upgrade all deps and solve security vulnerabilities

package.json
GH-56
dist folder should not be commited to git repo via semantic release
Fixes #56 
=> fix(ci-cd): remove dist as a part of semantic

package-lock.json, package.json
GH-58
changes related to semantic
Fixes #58 
=> fix(ci-cd): changes related to semantic

package-lock.json
gh-71
fix the vulnerability of moment
Fixes #71
=> chore(deps): fix the vulnerability of moment

package-lock.json, package.json
GH-77
Updated non loopback dependencies as well
Fixes #77 
=> chore(deps): update non loopback dependencies

package-lock.json, package.json
added overrides to remove vulnerabilities
GH-100
Removed vulnerabilities
Fixes #100 
=> fix(deps): remove vulnerabilities

package-lock.json, package.json
reverting the breaking change by version update
GH-118
reverting the breaking change by version update of @aws-sdk/client-s3
Fixes #118 
=> chore(deps): reverting the breaking change by version update

.sonarcloud.properties, src/types.ts
resolving sonar smells to improve quality gate
Fixes # (GH-110)
=> fix(chore): fixing sonar smells

.github/workflows/release.yaml
release will be via the workflow file
BREAKING CHANGE:
remove support for node 16
GH-159
add release github workflow
Fixes #159 
=> feat(ci-cd): add release github workflow

.github/workflows/sync-docs.yaml
update the readme path in sync docs workflow
Fixes # (issue)
=> chore(core): update the readme path in sync docs workflow

.github/workflows/main.yaml, .github/workflows/release.yaml, package-lock.json, package.json
add the ci workflow for pr
GH-191
step to generate changelog
add the ci workflow for pr
Fixes #191 
=> fix(ci-cd): step to generate changelog
